import type { StoryEvent } from "../story-types";

// Metadata only: the original state machines remain the sole performance scripts.
export const EXTERNAL_STORY_EVENTS: StoryEvent[] = [
  { id: "main.prologue.arrival", title: "Day 1 序章／抵達海島", summary: "完整序章，包含走位、播種、釣魚及料理教學。", chapter: "prologue", characters: ["mayor", "captain"], priority: 0, once: true, execution: "external", debug: { category: "main", weather: "clear" }, conditions: [{ type: "map", mapId: "port" }, { type: "day", min: 0, max: 0 }], steps: [] },
  { id: "main.day2.arrivals", title: "Day 2 木匠與藝術家初登場", summary: "村長來訪、碼頭接人、選屋、採集及修繕，接續露比事件。", chapter: "day2", characters: ["mayor", "carpenter", "artist"], priority: 0, once: true, execution: "external", debug: { category: "intro", weather: "clear" }, conditions: [{ type: "map", mapId: "livingArea" }, { type: "day", min: 1, max: 1 }, { type: "phase", min: 8 / 24, max: 8.5 / 24 }], steps: [] },
  { id: "character.botanist.arrival", title: "Day 3 植物學家初登場", summary: "現有克拉拉來訪及花田事件。", chapter: "day3", characters: ["botanist"], priority: 0, once: true, execution: "external", debug: { category: "intro", weather: "clear" }, conditions: [{ type: "day", min: 2, max: 2 }, { type: "phase", min: 10 / 24, max: 10.5 / 24 }], steps: [] },
  { id: "character.oceanographer.arrival", title: "Day 3 海洋學家初登場", summary: "現有海洋學家來訪事件。", chapter: "day3", characters: ["oceanographer"], priority: 0, once: true, execution: "external", debug: { category: "intro", weather: "clear" }, conditions: [{ type: "day", min: 2, max: 2 }, { type: "phase", min: 14 / 24, max: 16 / 24 }], steps: [] },
  { id: "character.carpenter.legacy_movein", title: "木匠入住收尾（舊流程）", summary: "既有 carpenter-quest 入住對話；引用 carpenter_movein CG。", chapter: "legacy", characters: ["carpenter"], priority: 0, once: true, execution: "external", debug: { category: "special" }, conditions: [{ type: "map", mapId: "oldVillage" }], steps: [] },
  { id: "character.artist.personal", title: "Day 2 露比個人事件", summary: "現有藝術家選屋、採花與研磨顏料流程。", chapter: "day2", characters: ["artist"], priority: 0, once: true, execution: "external", debug: { category: "intro", weather: "clear" }, conditions: [{ type: "map", mapId: "oldVillage" }, { type: "day", min: 1, max: 1 }], steps: [] },
  { id: "character.chef.arrival", title: "廚師碼頭初登場", summary: "現有廚師碼頭見面對話。", chapter: "chef", characters: ["chef", "mayor"], priority: 0, once: true, execution: "external", debug: { category: "intro" }, conditions: [{ type: "map", mapId: "port" }], steps: [] },
  { id: "character.chef.house", title: "廚師選屋", summary: "現有廚師空屋與共餐條件對話。", chapter: "chef", characters: ["chef"], priority: 0, once: true, execution: "external", debug: { category: "special" }, conditions: [{ type: "map", mapId: "oldVillage" }], steps: [] },
  { id: "character.chef.movein", title: "廚師入住", summary: "現有廚師民宿開張收尾。", chapter: "chef", characters: ["chef"], priority: 0, once: true, execution: "external", debug: { category: "special" }, conditions: [{ type: "map", mapId: "oldVillage" }], steps: [] },
];
