import { gameState, inventory } from "./game-state";
import { animals } from "./npc-runtime";
import { showUiToast } from "./ui-toast";
import type { ContextAction } from "./context-interaction";
export type AnimalInteractionRecord = { lastPettedDay: number; lastHarvestDay: number };
const records: Record<string, AnimalInteractionRecord> = {}; let carriedAnimalId: string | null = null;
const recordFor = (id: string) => (records[id] ??= { lastPettedDay: -1, lastHarvestDay: -1 });
const animalName = (type: string) => type === "cow" ? "\u725b" : type === "sheep" ? "\u7f8a" : "\u96de";
const productFor = (type: string): "milk" | "wool" | "egg" => type === "cow" ? "milk" : type === "sheep" ? "wool" : "egg";
const productName = (type: string) => type === "cow" ? "\u725b\u5976" : type === "sheep" ? "\u7f8a\u6bdb" : "\u96de\u86cb";
export const isAnimalCarried = (id: string) => carriedAnimalId === id;
export const getCarriedAnimalId = () => carriedAnimalId;
export const canHarvestAnimal = (id: string) => recordFor(id).lastHarvestDay !== gameState.currentDay;
export const canCarryAnimal = (type: string) => type === "chicken";
export function petAnimal(id: string) { const animal = animals.find((a) => a.id === id); if (!animal) return; const record = recordFor(id); if (record.lastPettedDay === gameState.currentDay) { showUiToast("\u64ab\u6478", `\u4eca\u5929\u5df2\u7d93\u64ab\u6478\u904e${animalName(animal.type)}\u4e86\u3002`); return; } record.lastPettedDay = gameState.currentDay; showUiToast("\u64ab\u6478", `${animalName(animal.type)}\u770b\u8d77\u4f86\u5f88\u958b\u5fc3\u3002`); }
export function harvestAnimal(id: string) { const animal = animals.find((a) => a.id === id); if (!animal || !canHarvestAnimal(id)) return; const product = productFor(animal.type); inventory.animalProducts[product]++; recordFor(id).lastHarvestDay = gameState.currentDay; showUiToast("\u6536\u6210", `${productName(animal.type)} +1`); }
export function carryAnimal(id: string) { const animal = animals.find((a) => a.id === id); if (!animal || !canCarryAnimal(animal.type) || carriedAnimalId) return; carriedAnimalId = id; animal.wanderState = "carried"; showUiToast("\u62b1\u8d77", `\u62b1\u8d77\u4e86${animalName(animal.type)}\u3002`); }
export function dropCarriedAnimal() { if (!carriedAnimalId || !gameState.player) return; const animal = animals.find((a) => a.id === carriedAnimalId); carriedAnimalId = null; if (!animal) return; const fx = -Math.sin(gameState.player.rotation.y), fz = -Math.cos(gameState.player.rotation.y); animal.mesh.position.set(gameState.player.position.x + fx * 0.9, 0, gameState.player.position.z + fz * 0.9); animal.wanderState = "resting"; animal.restUntil = gameState.elapsed + 1; showUiToast("\u653e\u4e0b", `\u653e\u4e0b\u4e86${animalName(animal.type)}\u3002`); }
export function updateCarriedAnimalPose() { if (!carriedAnimalId || !gameState.player) return; const animal = animals.find((a) => a.id === carriedAnimalId); if (!animal) { carriedAnimalId = null; return; } const fx = -Math.sin(gameState.player.rotation.y), fz = -Math.cos(gameState.player.rotation.y); animal.mesh.position.set(gameState.player.position.x + fx * 0.42, gameState.player.position.y + 0.82, gameState.player.position.z + fz * 0.42); animal.mesh.rotation.y = gameState.player.rotation.y; }
export function actionsForAnimal(id: string): ContextAction[] { const animal = animals.find((a) => a.id === id); if (!animal) return []; if (carriedAnimalId === id) return [{ id: "drop", label: "\u653e\u4e0b", slot: "primary", execute: dropCarriedAnimal }]; if (carriedAnimalId) return []; const actions: ContextAction[] = [{ id: "pet", label: "\u64ab\u6478", slot: "primary", execute: () => petAnimal(id) }]; if (canHarvestAnimal(id)) actions.push({ id: "harvest", label: "\u6536\u6210", slot: "secondary", execute: () => harvestAnimal(id) }); if (canCarryAnimal(animal.type)) actions.push({ id: "carry", label: "\u62b1\u8d77", slot: "tertiary", execute: () => carryAnimal(id) }); return actions; }
export function exportAnimalInteractionState() { return { records: JSON.parse(JSON.stringify(records)), carriedAnimalId }; }
export function restoreAnimalInteractionState(data: unknown) { Object.keys(records).forEach((id) => delete records[id]); const saved = data && typeof data === "object" ? data as any : {}; Object.entries(saved.records || {}).forEach(([id, value]) => { const item = value as any; records[id] = { lastPettedDay: Number.isFinite(item?.lastPettedDay) ? item.lastPettedDay : -1, lastHarvestDay: Number.isFinite(item?.lastHarvestDay) ? item.lastHarvestDay : -1 }; }); carriedAnimalId = typeof saved.carriedAnimalId === "string" && animals.some((animal) => animal.id === saved.carriedAnimalId) ? saved.carriedAnimalId : null; }
